### PR TITLE
Updated check of target-inventory

### PR DESCRIPTION
**Pull request by johannesmateboer**

### CODE REVIEW

**Comment by deirn** [comment]
Can you explain what this PR does?

**Comment by johannesmateboer** [comment]
It checks every targetslot. The way it was, the slotposition of the sourcestack (var j) was used to check if the target has at that very same spot, space to put the stack. In this change, the target is iterated to find a proper slot. This means that the source-slot doesn't decide what the target-slot will be, it just looks for space.

**Comment by deirn** [comment]
that check's already on `merge` though, i guess the `isValid` check is still useless though
https://github.com/badasintended/slotlink/blob/a58f4c7fa08e9998ab2dacb6ab2fe831c9734d3d/src/main/kotlin/badasintended/slotlink/inventory/FilteredInventory.kt#L28-L45

**Comment by johannesmateboer** [comment]
I discovered this issue with Reborn Core. The machines of TechReborn (i.e.) have an inventory-system which is a little complex. "Just" checking their inventory almost always works, because they have an inventory. That means that `var target = getStack(slot) `
always will return something: the actual inventory, a so-called OptionalInventory or an empty inventory. 

However, that means that `if (!isValid(slot, one)) return` has a problem: it cannot identify the problem correctly, so it returns true. As you said: this method is not very useful. Then this check happens:
```
override fun canInsert(slot: Int, stack: ItemStack, dir: Direction?): Boolean {
       return isValid(stack) and ((inventory as? SidedInventory)?.canInsert(slot, stack, dir) ?: true)
}
```
isValid checks out, but then we want RebornCore to check a SidedInventory on a specific slot with a specific direction. And that check fails inside RebornCore when you have changed the input/output-sides of the machine while(!) being connected to an export-link. 
Slotlink tells Reborn: 'check slot x on side y for accepting stack z'. Reborn fails, because that combination errors to null. It was there, but it was changed. Slotlink is sure that it exists, RebornCore doesn't know how to solve that, because it doesn't exist, so there's a NullException.

By checking each target-slot individually before accessing any of its properties or methods (my proposed change), that problem is solved. RebornCore may throw NullExceptions, inventories may change, but my proposed change makes sure that Slotlink works with an inventory that is accessible at the specified slot, with the specified stack, on the specified side.

**Pull request closed without merging**
